Update yaml.mdx: fix bug (#370)
For the given example for documentation:

```py
from agno.agent import Agent
from agno.tools.duckduckgo import DuckDuckGoTools
from agno.storage.yaml import YamlStorage

agent = Agent(
    storage=YamlStorage(path="tmp/agent_sessions_yaml"),
    tools=[DuckDuckGoTools()],
    add_history_to_messages=True,
)

agent.print_response("How many people live in Canada?")
agent.print_response("What is their national anthem called?")
```

The YamlStorage doesn't have `path` argument anymore:
```py
Traceback (most recent call last):
  File "/home/dgideas/ai/storage_yaml.py", line 10, in <module>
    storage=YamlStorage(path="tmp/agent_sessions_yaml"),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: YamlStorage.__init__() got an unexpected keyword argument 'path'
```

Now we use `dir_path` instead of `path`. This commit fix this issue.

Co-authored-by: Yash Pratap Solanky <101447028+ysolanky@users.noreply.github.com>